[project]
name = "pykline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Daic", email = "214939381@qq.com" }
]
requires-python = ">=3.8"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
